name: ShellCheck

on: [push, pull_request]

jobs:
  shellcheck:
    name: Run shellcheck via pre-commit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pre-commit shellcheck

    - name: Run shellcheck via pre-commit
      run: pre-commit run shellcheck --all-files
